version: "3.3"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass development
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /$PWD/database-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  bullboard:
    container_name: bullboard
    image: deadly0/bull-board
    restart: always
    ports:
      - 6543:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: development
      REDIS_USE_TLS: "false"
      BULL_PREFIX: bull
    depends_on:
      - redis
